package com.example.text;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.Button;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Button btn1 = findViewById(R.id.btn);
        Button dialerBtn = findViewById(R.id.dialer);
        dialerBtn.setText("Dialer btn");
        Button msg = findViewById(R.id.btn_msg);

        msg.setText("Send message");
        Button email = findViewById(R.id.email);

//            btn.setOnClickListener(v->{
//                Log.d("msg", btn.getText().toString());
//            });
        check(btn1);

        dialerBtn.setOnClickListener(v->{
            Intent i_dialer = new Intent(Intent.ACTION_DIAL);
            i_dialer.setData(Uri.parse("tel:+8801772258677"));
            startActivity(i_dialer);
        });

        msg.setOnClickListener(v->{
            Intent send_msg = new Intent(Intent.ACTION_SENDTO);
            send_msg.setData(Uri.parse("smsto:"+Uri.encode("+8801772258677")));
            send_msg.putExtra("sms_body", "Hello data ♥");
            startActivity(send_msg);
        });

        email.setOnClickListener(v->{
            Intent email_sender = new Intent(Intent.ACTION_SEND);
            email_sender.setType("message/rfc822").putExtra(Intent.EXTRA_EMAIL, new String[]{"admin@ishwardy.com"});

            email_sender.putExtra(Intent.EXTRA_SUBJECT, "Demo mail generated by Email")
                    .putExtra(Intent.EXTRA_TEXT, "Dummy body");
            startActivity(Intent.createChooser(email_sender, "Send a dummy email"));

        });




    }

    public void check(Button btn){
        btn.setOnClickListener(v->{
                Log.d("msg", btn.getText().toString());
            });
    }
}